### ISSUE TITLE
styles.min.css not found using cross links

### ISSUE THREAD

**Issue by dwinkler1** [benwebber/tiddlywiki-plugins#4]
I'm fairly new to TW so sorry if this is my error. When I use the environment variable method of installing cross links globally in a Node.js installation I get the error that `styles.min.css` is not found. Copying `styles.css` to that name fixes it.

**Comment by benwebber** [comment]
This project uses [Tailwind CSS](https://tailwindcss.com/). The CSS files under `src/` are incomplete; we generate the final CSS in a build step.

Copying `styles.css` to `styles.min.css` will fix that error message, but it won't actually install the intended style sheet. If you drag the plugin to your own wiki instead, you'll get the generated CSS.

I hadn't considered the plugin directory installation method because I don't use the Node.js version. Do you need to use the directory method for a particular reason?

**Comment by dwinkler1** [comment]
Thank you for your explanation. I'm trying to wrap my head around the Node.js version but it seems like there is no real downside to just importing by dragging into the wiki.
